version: '3.8'

services:
  # FIREWALL
  firewall:
    build: ./firewall
    container_name: firewall
    hostname: firewall
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      net.ipv4.ip_forward: 1
    networks:
      rede_interna:
        ipv4_address: 172.20.0.2
      rede_dmz:
        ipv4_address: 172.21.0.2
      rede_servicos:
        ipv4_address: 172.22.0.2

  # SERVIDOR WEB
  web:
    build: ./web
    container_name: web
    hostname: web
    depends_on:
      - firewall
    networks:
      rede_dmz:
        ipv4_address: 172.21.0.10

  # BANCO DE DADOS
  db:
    image: postgres:13-alpine
    container_name: db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on:
      - firewall
    networks:
      rede_servicos:
        ipv4_address: 172.22.0.10

  # MÁQUINA CLIENTE
  client:
    image: alpine:latest
    container_name: client
    hostname: client
    depends_on:
      - firewall
    command: sh -c "apk update && apk add --no-cache curl bind-tools net-tools iproute2 netcat-openbsd && tail -f /dev/null"
    networks:
      rede_interna:
        ipv4_address: 172.20.0.10

networks:
  rede_interna:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.2
  rede_dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.2
  rede_servicos:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.2
